from OTAnalytics.domain import event

ROAD_USER_ID = event.ROAD_USER_ID
ROAD_USER_TYPE = event.ROAD_USER_TYPE
HOSTNAME = event.HOSTNAME
OCCURRENCE = event.OCCURRENCE
OCCURRENCE_DATE = "occurrence_day"
OCCURRENCE_TIME = "occurrence_time"
FRAME_NUMBER = event.FRAME_NUMBER
SECTION_ID = event.SECTION_ID
SECTION_NAME = "section_name"
EVENT_COORDINATE = event.EVENT_COORDINATE
EVENT_COORDINATE_X = "coordinate_px_x"
EVENT_COORDINATE_Y = "coordinate_px_y"
EVENT_TYPE = event.EVENT_TYPE
DIRECTION_VECTOR = event.DIRECTION_VECTOR
DIRECTION_VECTOR_X = "vector_px_x"
DIRECTION_VECTOR_Y = "vector_px_y"
VIDEO_NAME = event.VIDEO_NAME
INTERPOLATED_OCCURRENCE = event.INTERPOLATED_OCCURRENCE
INTERPOLATED_EVENT_COORDINATE_X = "interpolated_coordinate_px_x"
INTERPOLATED_EVENT_COORDINATE_Y = "interpolated_coordinate_px_y"

DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT = "%H:%M:%S.%f"
DATE_TIME_FORMAT = f"{DATE_FORMAT} {TIME_FORMAT}"
