---
# This workflow will install Python dependencies, run tests

name: Run CI/CD

on: push

jobs:
  build-n-publish:
    name: Build and upload release to PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    environment:
      name: testpypi
      url: https://test.pypi.org/project/OTAnalytics-EXAMPLE-TEST-DISTRIBUTION-RSENG
    permissions:
      actions: read
      contents: read
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
