---
name: Publish to TestPyPI

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  test:
    uses: './.github/workflows/test.yml'
  regression-test:
    uses: './.github/workflows/regression-test.yml'
    secrets: inherit
  publish-to-testpypi:
    runs-on: ubuntu-latest
    needs:
      - test
      - regression-test
    environment:
      name: testpypi
      url: https://test.pypi.org/p/OTAnalytics
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Update Python Package Version
        uses: platomo/update-version-py-action@v1
        with:
          version: nightly
          file-path: "OTAnalytics"
      - name: Publish Python Package
        uses: platomo/publish-pypi-action@v1.0.1
