---
name: Publish to TestPyPI

on:
  push:
    branches:
      - main

permissions: read-all

env:
  out_dir: "dist/"

jobs:
  test:
    uses: "./.github/workflows/test.yml"
  regression-test:
    uses: "./.github/workflows/regression-test.yml"
    secrets: inherit
  publish-to-testpypi:
    runs-on: ubuntu-latest
    needs:
      - test
      - regression-test
    environment:
      name: testpypi
      url: https://test.pypi.org/p/OTAnalytics
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Update Python Package Version
        uses: platomo/update-version-py-action@v1.0.1
        with:
          version: nightly
          file-path: "OTAnalytics"
      - name: Install pypa/build
        shell: bash
        run: |
          python3 -m pip install build --user

      - name: Build a binary wheel and a source tarball
        shell: bash
        run: python -m build --outdir ${{ env.out_dir }}

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: ${{ env.out_dir }}

      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ vars.PYPI_REPO_URL }}
